name: ipay_money_flutter_sdk
description: A payment method flutter package from the i-pay.money platform.
version: 0.0.2
homepage: https://i-pay.money
repository: https://github.com/kodjomoustapha/ipaymoney-sdk-flutter

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  random_string: ^2.3.1
  flutter_riverpod: ^2.2.0
  webview_flutter: ^4.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

