name: ipay_money_flutter_sdk
description: Un package flutter de moyen de paiement de la plateforme iPay Money.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  random_string: ^2.3.1
  flutter_riverpod: ^2.0.2
  enum_to_string: ^2.0.1
  webview_flutter: ^3.0.4
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

